### ISSUE TITLE
could you please show the detail of processing TAB-seq data?

### ISSUE THREAD

**Issue by yangjim221** [zhiyhu/CAPS-paper#1]
I want to repeat the figure 2e in the CAPS-paper. According to your code, I can get similar correlation between CAPS and ACE-seq. However, I don't know how to process the TAB-seq data. Thank you!

**Comment by zhiyhu** [comment]
[config.yaml.txt](https://github.com/zhiyhu/CAPS-paper/files/8318938/config.yaml.txt)
[Snakefile.txt](https://github.com/zhiyhu/CAPS-paper/files/8318939/Snakefile.txt)

Hi, here are the Snakemake scripts I wrote for preprocessing TAB-seq data. Hope it helps!

**Comment by yangjim221** [comment]
Thanks for your detailed scripts. And I will have a try as soon as possible. :)
